apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-submission-frontend
  template:
    metadata:
      labels:
        app: grade-submission-frontend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: grade-submission-frontend
        image: ghcr.io/rochdy/keeper-frontend:6f71cb9e00cd04a3647643241a7e16c5e42c8c5d
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
